### ISSUE TITLE
Update with support for ERC721Votes

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/contracts-wizard#101]
- [x] Add "Votes" option in ERC721 tab
- [x] Update "ERC20Votes" option in Governor tab to reflect it also works with ERC721Votes (no changes needed in the code, just the label)

**Comment by codesport** [comment]
@ericglau,

 Under the [ERC721 tab](https://wizard.openzeppelin.com/#erc721), when `Votes `checkbox is selected, I noticed that the votes option still imports `ERC721.sol`.

Would this import be needed?  [draft-ERC721Votes.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.5.0/contracts/token/ERC721/extensions/draft-ERC721Votes.sol) also imports ERC721.sol. 

I'm thinking this is redundant.  But I may be wrong.

**Comment by ericglau** [comment]
Hi @codesport, you are right that since `draft-ERC721Votes.sol` already imports `ERC721.sol`, it isn't strictly necessary to import `ERC721.sol` in the template.  However, it is fine to include it for clarity, since the template inherits from it directly and this can help to avoid errors in case you decide to change the code later to not use the `draft-ERC721Votes.sol` extension.

**Comment by codesport** [comment]
@frangio 

Didn't know imports and inheritance within solidity worked like that without causing headaches.

Definitely appreciate the clarity and your explanation!
