### ISSUE TITLE
Remix now supports deploying UUPS upgradeable contracts 

### ISSUE THREAD

**Issue by htadashi** [OpenZeppelin/contracts-wizard#155]
The new release (v0.25.0) of Remix IDE [added support for UUPS upgradeable contracts](https://github.com/ethereum/remix-project/releases/tag/v0.25.0) (see https://github.com/ethereum/remix-project/pull/2260 for the specific commit).
Thus, the warning tooltip introduced in #63 can be removed if the UUPS option is selected.

**Comment by frangio** [comment]
We should test it to understand how it works. I'm specifically wondering about initialization. We might still need a "warning" tooltip to tell people that they have to call the initializer manually.

**Comment by joaofreires** [comment]
@htadashi is it possible to have the `Deploy with Proxy` enabled by [customized url params](https://remix-ide.readthedocs.io/en/latest/locations.html#customize-remix-with-url-parameters)?

**Comment by htadashi** [comment]
@frangio Good point, this is important. But I think better than alerting in a tooltip would be if Remix would have a "Deploy proxy and initialize" option enabled as a default.

@joaofreires In this way, the Contract Wizard wouldn't even need to pass a custom url param when opening the source code in Remix.

What do you think? If it makes sense, I could open an issue in Remix and reference this issue there.

**Comment by frangio** [comment]
I don't think it makes sense for Remix to have "Deploy with Proxy" as the default. Not sure if that was the proposal.

@joaofreires Suggestion is really good, if this isn't possible we should definitely open an issue in Remix.

**Comment by joaofreires** [comment]
I took a brief look into the remix proxy support PR: https://github.com/ethereum/remix-project/pull/2260 , more specifically at: `libs/remix-core-plugin/src/lib/openzeppelin-proxy.ts`.

Looks like Remix identify by itself if the contract is an OpenZeppelin proxy or not. I don't know if it is this worse for them to have the proxy enabled by default, since they know the context to apply it. Though, this is a Remix decision.

The most we can do right now is @frangio suggestion:
> We might still need a "warning" tooltip to tell people that they have to call the initializer manually.

**Comment by htadashi** [comment]
@frangio I was thinking if it would make sense to add a "Deploy with proxy and initialize" option and make it enabled as the default whenever Remix detects a UUPS contract - something similar to this mockup:
![image](https://user-images.githubusercontent.com/2355491/180598160-d1322033-ddb5-40f9-8a1d-fa0a3692dc5c.png)

My reasoning was that users could ignore the tooltip alerting them to call the initializer manually if the button "Open in Remix" is enabled (and clicking on it directly opens the contract in Remix instead of forcing them to read the tooltip). However, @joaofreires last comment changed my mind since I am not sure if this would be a good decision in Remix side.

**Comment by ioedeveloper** [comment]
@htadashi I don't see why a tooltip alerting users to call the initializer manually is required because, remix automatically calls the `intialize` function on deploy when `"deploy with proxy"` is checked. I think the suggestion of @joaofreires is good to have a customized url param that enables `"deploy with proxy"` by default.

**Comment by MatiFalcone** [comment]
Is there an example or tutorial on how to achieve this? Thank you!

**Comment by ericglau** [comment]
@MatiFalcone Remix has some documentation on this: https://remix-ide.readthedocs.io/en/latest/run_proxy_contracts.html
