### ISSUE TITLE
Unnecessary inheritance on generated contract

### ISSUE THREAD

**Issue by htadashi** [OpenZeppelin/contracts-wizard#41]
First of all, I'd like to thank OpenZeppelin's team for developing this contract generator. It helped me many times and I'm sure it is very useful for many others developers.

In the generated contract, it seems that we have unnecessary inheritance depending on the choice of the toggles: ERC20Burnable, ERC20Snapshot and ERC20Snapshot inherit ERC20 already, so there is no need to inherit it ERC20 again in the generated contract, right? (The same can be said regarding ERC721 and ERC1155)

However, I am not sure if it is worthy to change the code to avoid the unnecessary inheritance, as it doesn't really make a difference in terms of deployment gas. On the other hand, I saw this unnecessary inheritance being pointed out on some OpenZeppelin audits, so I think it may have pedagogical value (in the sense of teaching developers how to write better code).

**Comment by frangio** [comment]
Thanks for pointing this out @htadashi!

It's true that some parents are technically unnecessary. To be honest, doing things this way makes the code generation easier for us. :slightly_smiling_face:  But I would also say it can serve a good purpose in some cases to spell out all relevant parents, such as when using upgradeability because you need to remember to initialize those parents manually. The Wizard will correctly initialize all parents already, but I'd say this is also a good practice that I'd want to teach.

**Comment by htadashi** [comment]
Thanks for the explanation @frangio :)
The new upgradeability toggles are great!
