### ISSUE TITLE
Bug in ERC-721 Burnable modifier

### ISSUE THREAD

**Issue by nnnnicholas** [OpenZeppelin/contracts-wizard#47]
The ERC-721 `_burn` function is erroneously applied to the contract only when URI Storage is activated. See screenshots for clarification.

![image](https://user-images.githubusercontent.com/1418561/127048389-0b1e2565-7e2a-493d-b440-70d3e2a3d16b.png)
![image](https://user-images.githubusercontent.com/1418561/127048405-51951eda-dded-4fc8-bce3-5407fb1c1dcd.png)

**Comment by frangio** [comment]
Thanks for reporting @nnnnicholas.

This is not a bug but an unfortunate feature of Solidity. Since `ERC721URIStorage` overrides `_burn` to add some URI-related logic, Solidity forces you to manually "resolve" this with an explicit override in the final contract.

We're going to add a comment in the code that the Wizard creates to make it clear that some of these functions are merely boilerplate required by Solidity.

**Comment by nnnnicholas** [comment]
Thank you. Apologies for reporting a non-bug.
