### ISSUE TITLE
Warn about opening in Remix when choosing upgradeability

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/contracts-wizard#63]
The user may not be aware that upgradeable contracts have to be deployed behind a proxy, and deploying with Remix may produce unexpected results. [Example support request.](https://forum.openzeppelin.com/t/wizard-generated-erc20-issue/16524)

**Comment by auryn-macmillan** [comment]
Was just coming here to post this.
Would be great if you could also easily deploy the proxy in Remix.

**Comment by frangio** [comment]
Added a warning in https://github.com/OpenZeppelin/contracts-wizard/commit/c5c84fabe496ad2b5988553c0f1783dc33e78eed.

**Comment by cyanlink** [comment]
Sorry for bothering but as a new comer I find the warning easily overlooked as it only shows as a bubble dialog on mouse hover. This information is not very accessible by Googling either. At least we should show a static noticeable warning message "⚠ Remix cannot be used for upgradeable contracts " next to the "Open in Remix" option IMO.

**Comment by frangio** [comment]
Thanks for the suggestion @cyanlink. Do you suggest the warning should be visible even before selecting upgradeability?

**Comment by cyanlink** [comment]
I would prefer not to because without upgradeability Remix IDE is all right. It's still conventional contract code that does not need extra setup. When upgradeability selected, a sudden appearance of a warning sign can better draw user's attention than a constant warning.

**Comment by cyanlink** [comment]
After going back to the wizard website I reconsidered. The warning should be displayed in a even more noticeable way, because the webpage is scrollable, when we scroll down to select upgradeability, then scroll back to top to reach the export buttons, we might still overlook if the appeared warning is placed near the buttons. 

Maybe it should be right under the Upgradeability options section when toggled; or we can even pop up a modal dialog for acknowledgement when user try to open in remix when toggled.

**Comment by frangio** [comment]
Ok, in https://github.com/OpenZeppelin/contracts-wizard/commit/e42c3fb1f2fbf0ee0948bbbf3a004bb91cadc95e I've made it so the button is disabled for upgradeable contracts and actually opening in Remix requires an additional click inside the tooltip. 

Check it out please!
